from django.urls import path
from main import views as main_views

app_name = 'main'

urlpatterns = [
    path('', main_views.main, name='main'),
    path('tutorial/python/python_default/', main_views.python, name='python'),
    path('tutorial/python/python_installing/', main_views.python_installing, name='python_installing'),
    path('tutorial/python/data_types/', main_views.data_types, name='data_types'),
    path('tutorial/python/indentation/', main_views.indentation, name='indentation'),
    path('tutorial/python/date&time/', main_views.date_time, name='date_time'),
    path('tutorial/python/list/', main_views.python_list, name='python_list'),
    path('tutorial/python/set/', main_views.python_set, name='python_set'),
    path('tutorial/python/tuple/', main_views.python_tuple, name='python_tuple'),
    path('tutorial/python/dictionary/', main_views.python_dict, name='python_dict'),
    path('tutorial/python/operators/', main_views.python_operators, name='python_operator'),
    path('tutorial/python/global&local_variables/', main_views.python_global_local_variables,
         name='python_local_global'),
    path('tutorial/python/if&elif&else_conditions/', main_views.python_conditions, name='python_if_elif_else'),
    path('tutorial/python/loop/', main_views.python_loop, name='python_loop'),
    path('tutorial/python/array/', main_views.python_array, name='python_array'),
    path('tutorial/python/heapq&count/', main_views.python_heapq_enum, name='python_heapq_enum'),
    path('tutorial/python/user_input&output/', main_views.python_input_output, name='python_i&o'),
    path('tutorial/python/python_files&folders/', main_views.python_files_folders, name='python_files_folders'),
    path('tutorial/python/python_os&python_path/', main_views.python_os_path, name='python_os_path'),
    path('tutorial/python/python_function/', main_views.python_function, name='python_function'),
    path('tutorial/python/python_lambda/', main_views.python_lambda, name='python_lambda'),
    path('tutorial/python/python_recursion/', main_views.python_recursion, name='python_recursion'),
    path('tutorial/python/python_search&python_filter/', main_views.python_search_filter, name='python_search_filter'),
    path('tutorial/python/python_map&python_reduce/', main_views.python_map_reduce, name='python_map_reduce'),
    path('tutorial/python/python_sort&min_max/', main_views.python_sort_min_max, name='python_sort_min_max'),
    path('tutorial/python/python_module&python_package/', main_views.python_module_package,
         name='python_module_package'),
    path('tutorial/python/python_print_function/', main_views.python_print_function, name='python_print_function'),
    path('tutorial/python/python_copy_function/', main_views.python_copy_function, name='python_copy_function'),
    path('tutorial/python/python_name_variable/', main_views.python_name_variable, name='python_name_variable'),
    path('tutorial/python/python_pip-package-manager/', main_views.python_pip, name='python_pip'),
    path('tutorial/python/python_urllib/', main_views.python_urllib, name='python_urllib'),
    path('tutorial/python/python_console/', main_views.python_console, name='python_console'),
    path('tutorial/python/python_tempfile/', main_views.python_tempfile, name='python_tempfile'),
    path('tutorial/python/python_descriptor/', main_views.python_descriptor, name='python_descriptor'),
    path('tutorial/python/python_decorator/', main_views.python_decorator, name='python_decorator'),
    path('tutorial/python/python_class/', main_views.python_class, name='python_class'),
    path('tutorial/python/python_regex/', main_views.python_regex, name='python_regex'),
    path('tutorial/python/python_args_kwargs/', main_views.python_args_kwargs, name='python_args_kwargs'),
    path('tutorial/python/python_mixins/', main_views.python_mixins, name='python_mixins'),
    path('tutorial/python/python_attribute_access/', main_views.python_attribute_access,
         name='python_attribute_access'),
    path('tutorial/python/python_exceptions/', main_views.python_exceptions,
         name='python_exceptions'),
    path('tutorial/python/python_hashlib/', main_views.python_hashlib,
         name='python_hashlib'),
    path('tutorial/python/python_design_patterns/', main_views.python_design_patterns,
         name='python_design_patterns'),

    path('tutorial/python/python_speed/', main_views.python_speed,
         name='python_speed'),
    path('tutorial/python/python_zip_unzip_files/', main_views.python_zip_unzip_files,
         name='python_zip_unzip_files'),
    path('tutorial/python/python_http_server/', main_views.python_http_server,
         name='python_http_server'),
    path('tutorial/python/python_generators/', main_views.python_generators,
         name='python_generators'),
    path('tutorial/python/python_string_manipulation/', main_views.python_string_manipulation,
         name='python_string_manipulation'),
    path('tutorial/python/python_debugging/', main_views.python_debugging,
         name='python_debugging'),
    path('tutorial/python/python_overriding/', main_views.python_overriding,
         name='python_overriding'),
    path('tutorial/python/python_polymorphism/', main_views.python_polymorphism,
         name='python_polymorphism'),
    path('tutorial/python/python_overloading/', main_views.python_overloading,
         name='python_overloading'),
    path('tutorial/python/python_inheritance/', main_views.python_inheritance,
         name='python_inheritance'),
    path('tutorial/python/python_hints/', main_views.python_hints,
         name='python_hints'),
    path('tutorial/python/python_multiprocessing/', main_views.python_multiprocessing,
         name='python_multiprocessing'),
    path('tutorial/python/python_multithreading/', main_views.python_multithreading,
         name='python_multithreading'),

    path('tutorial/python/python_networking/', main_views.python_networking,
         name='python_networking'),

    path('tutorial/python/python_virtual_environments/', main_views.python_virtual_environments,
         name='python_virtual_environments'),

    path('tutorial/python/python_unit_testing/', main_views.python_unit_testing,
         name='python_unit_testing'),

    path('tutorial/python/python_final/', main_views.python_final,
         name='python_final'),

    # --------------------------------------------------------
    path('quiz/', main_views.quiz, name='quiz'),
    path('article/', main_views.article, name='article'),
    path('algorithm/', main_views.algorithm, name='algorithm'),
    path('project/', main_views.project, name='project'),

]
