# Generated by Django 2.1.3 on 2020-07-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=1000)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Submission')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'db_table': 'Contact Form Table',
            },
        ),
    ]
