# Generated by Django 2.1.3 on 2020-07-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Submission'),
        ),
    ]
